# Generated by Django 5.1.1 on 2024-09-12 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Checkbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='account',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='transaction',
            managers=[
            ],
        ),
    ]
