# Generated by Django 5.1.1 on 2024-09-12 19:50

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Checkbook', '0002_alter_account_managers_alter_transaction_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='account',
            managers=[
                ('Accounts', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='transaction',
            managers=[
                ('Transactions', django.db.models.manager.Manager()),
            ],
        ),
    ]
